### ISSUE TITLE
[Feature] only show (some) UI when a scan is active

### ISSUE THREAD

**Issue by slippycheeze** [Balvald/ArtemisScannerTracker#19]
**Is your feature request related to a problem? Please describe.**
I'd love to have information on my scan progress while I'm scanning things.  I do love it.  Thank you!

I'd also like to keep the information EDMC displays relevant to my current activities.  Ideally, nothing that I don't care about should be present (eg: mission status, when I'm not doing them, system scan status when not exploring), but definitely nothing that I *don't* care about should be there.

Right now AST displays a bunch of information slots that I don't care about except when I'm actively scanning, all the time.  😿 

**Describe the solution you'd like**
I can tell you what I'd do to make this happen, but really, all I care about is that I don't see "empty" slots where data could be, but currently isn't.  So, *to me* the "time when a field is relevant" is:

| field | when to show |
| --- | --- |
| Last Exobiology Scan: | scan_progress > 0 |
| Last Species:         | scan_progress > 0 |
| Scan Progress:        | scan_progress > 0, and only if it isn't show elsewhere (eg: in `AST_state`) |
| System of last Scan:  | scan_progress > 0, and != current_system |
| Body of last Scan:    | scan_progress > 0, and != current_body |
| Unsold Scan Value:    | value > 0 |
| Current System:       | never - other plugins show this, but there is a pref, so that ok |
| Current Body:         | never - other plugins show this, but there is a pref, so that ok |

**Describe alternatives you've considered**
This is my first port of call.  If you don't like the idea, which is completely cool BTW, I'll probably
just go ahead and write my own.  I am just lazy, haha ;)

but seriously, I can't think of a better alternative than "only show the line if" as per the table above,
but I'd be fine with *anything* that achieved my goal of only showing information when I care about it,
and probably perfectly happy with 80 percent of that lot, TBH.

**Additional context**
I hacked this locally to test it, just hiding everything when `plugin.AST_current_scan_progress > 0:`, which more or less works.  It just isn't very elegant, and isn't a full implementation ... and I don't really want to carry a local patch or fork.   

That is just dumb, when someone built an awesome tool already.  Especially because I bet it isn't as easy as it seems from the outside, haha. ;)

**Comment by Balvald** [comment]
> Scan Progress: | scan_progress > 0, and only if it isn't show elsewhere (eg: in AST_state)
Without scan_progress > 0 its covered with the prefs. The original idea was to have either never show AST_state but all the values that make AST_state or only show AST_state and have the elements that make up AST_state stay hidden.

Just to clarify, scan_progress > 0 is true all the time unless you press RESET once in the preferences which specifically sets it to "0/3" or then you first install the plugin. If having to press RESET was already part of the original proposal, then the 2nd Variant would work essentially the same.

1st Variant (User doesn't have to actively do something to have it hide while playing)

If it should happen automatically then only time I could think of is after selling it should hide non relevant bits but have the option to show them again
A Tickbox in prefs: _hide irrelevant fields/old info after selling._
A button in the prefs to force it to switch if it should now show/hide it.
replace "scan_progress = 0" for hiding with "we've just sold"

2nd Variant (user actively presses everytime on their own accord to hide things.):

A button/pref that hides everything (irrelevant) until the next scan (including itself if its part of the ui) when pressed/ticked.
Add the option to switch the state back to show it again in preferences if it is not exclusively in the preferences.
If its the latter it'd be another tickbox.

From those two I'm leaning towards the 1st one.

Thoughts? @slippycheeze

**Comment by Balvald** [comment]
variant 1 is on https://github.com/Balvald/ArtemisScannerTracker/tree/19-auto-hide-elements-option now.

It should work, will do some additional testing either tomorrow or after Christmas on this one.

**Comment by Balvald** [comment]
adding a second option to automatically hide not after selling all but also after finishing a full scan. just in case that was meant with the scan progress is at 0.

**Comment by Balvald** [comment]
Now I'll close. Check the state of it on the dev branch.

Reopen if there is need for clarification on either side, or I misinterpreted an aspect of how it should work.

**Comment by Balvald** [comment]
After release of v0.2.1 check that one instead.

Reopen if there is need for clarification on either side, or I misinterpreted an aspect of how it should work.
