### ISSUE TITLE
Feature Request -- Add Clonal Colony Range

### ISSUE THREAD

**Issue by luctius** [Balvald/ArtemisScannerTracker#2]
It would be nice if the plugin shows the minimum distance we should travel before make the next scan for this species.

**Comment by Balvald** [comment]
I'll wait to implement this one after I'm done with what I'm currently still brewing on my dev branch (General tracking of sold and unsold but already scanned biodata, atleast to the best of anyones abilities and current worth of scans not sold yet)

As I'd personally like it if I could check how far I've gone from the last scan while sitting in an SRV.
interpretation of this feature is to show the current distance to up to the last 2 scans.
Similar how in the Canonn plugin someone can select a surface signal and by using the proposed heading get to the place
only with the goal being to get far enough away from "temporarily" saved scan locations.

So far relevant notes for this feature as I did a little research of what it'd need:
- Lat, Long, Heading of current position can be found in Status.json as long as the player is close enough to a planet which is generally true while scanning biodata. Should be able to get this info in the plugin via ```dashboard_entry()```. Relevant: https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#player-dashboard
- Need the current planets radius to compute distance from different lat, long coordinates. -> Check Journals
- Save a current position somewhere upon scan if its not the final one. max. 2, needs lat, long, maybe radius depending when we can get the info how big the radius of the planet is.
- Get a list of colonial ranges for the different types of exobiology: https://canonn.science/codex/organic-scanning-challenge-primer/ _might_ not be fully exhaustive gotta check for any that might be missing gotta with the ingame Codex
- Show current distance to scanned positions and colonial range of last scanned exobiology
- Change colour of label showing current distance to the last scan position(s) (further away than colonial range = green, when not = yellow/orange)
- Maybe when heading towards an old scan position the corresponding label showing should be yellow, or red if already yellow.
- Stop showing the info after the 3rd and final Scan.
- Options to omit the Info from the plugin.
