### ISSUE TITLE
[Feature] abbreviate multi-million credit values

### ISSUE THREAD

**Issue by slippycheeze** [Balvald/ArtemisScannerTracker#30]
**Is your feature request related to a problem? Please describe.**
Once I'm looking at an unsold value of 158,209,100 Cr. a lot of those numbers stop being really meaningful.  The difference between 159,209,000 and 159,208,100 Cr. is quite small.  

The extra detail makes it harder to understand, at a glance, what my balance is.  (For me; I'm sure others don't experience the same.)

**Describe the solution you'd like**
I'd prefer to see "up to four significant digits" of value.  So, for example:
```
Value             Display
1,234             1,234 Cr.
12,345            12.34k Cr.
123,456           123.5k Cr.
1,234,567         1,234k Cr.
12,345,678        12.35m Cr.
123,456,789       123.5m Cr.
1,234,567,890     1,235m Cr.
```
Round to nearest (.0 - .499 => 0, .5 - .999 => 1) seems to work best with that.

**Describe alternatives you've considered**
Any shortening would be fine, really, if it kept to three or four digits.  Even five is probably fine to take in quickly, at a glance.

**Additional context**
I've used this before in displaying numbers where quick reference, at a glance comprehension was needed.  It was the best way I found to manage that; people "get" four numbers fast, without getting overwhelmed, but it still shows the "right" amount of detail for humans at each stage.

**Comment by Balvald** [comment]
Currently have a version of this on dev using SI prefixes so far.

each consecutive line is x10 the previous one gives this

```
1 Cr.
10 Cr.
100 Cr.
1.000 KCr.
10.00 KCr.
100.0 KCr.
1.000 MCr.
10.00 MCr.
100.0 MCr.
1.000 GCr.
10.00 GCr.
100.0 GCr.
1.000 TCr.
10.00 TCr.
100.0 TCr.
1.000 PCr.
.
.
.
```

Probably should force myself and make an extra case where the decimal point is directy after the first digit to be a thousand seperator instead and use the lower SI prefix because I just realized 1.000 KCr. could be misinterpreted as being 1,000 KCr. while actually just being 1 KCr.
