### ISSUE TITLE
[BUG] if you reset a 2/3 scan, the "Distance to Scan `#2`:" field is not cleared.

### ISSUE THREAD

**Issue by slippycheeze** [Balvald/ArtemisScannerTracker#32]
**Describe the bug**
If you reset a scan with two out of three samples, the "Distance to Scan `#2`:" field remains pointed at the second sample of the old exobio item.  

The "Distance to Scan `#1`:" field works fine, and when you take the second sample it correctly overwrites the second scan field.  No functional problems, just a somewhat confusing display.

**To Reproduce**
1. Scan any random exobio thing twice.  eg: get to Tussock Vigram (2/3)
2. Observe that Distance to Scan `#1` and `#2` fields are both populated.
3. Scan any *other* exobio thing, accepting the "will discard the partial sample" warning.
4. Observe that Distance to Scan `#1` is your newly scanned thing, but `#2` is still pointing to the previous sample.

(For maximum effect, travel to a new system between steps 2 and 3 ;)

**Expected behavior**
The second scan should be cleared.

**Desktop (please complete the following information):**
 - OS: Win 11
 - AST Version: 0.2.1
 - EDMC Version: latest.  sorry, can't quickly find the version, and I don't think it matters.

Thank you so much for all your hard work.

**Comment by slippycheeze** [comment]
wish there was a better way to avoid hyperlinking as issue references, sorry for spam.

**Comment by Balvald** [comment]
Just realised I also do not clear distances for the manual reset button in the preferences.
