### ISSUE TITLE
[BUG] in progress scan value (on the "Last Exobiology Scan:" line) always shows N/A now

### ISSUE THREAD

**Issue by slippycheeze** [Balvald/ArtemisScannerTracker#35]
**Describe the bug**
Since updating to the latest, 0.2.4, release the in-progress scans only show "N/A" value.   The accumulation of Unsold Scan Value does happen as expected.

**To Reproduce**
1. Enable in-progress scan value, if it isn't.
2. Scan something.

**Screenshots**

*cough*  I thought I had a 1/3 scan there, but this is 3/3.  anyway, the "N/A" is present all through the scan process.

![image](https://user-images.githubusercontent.com/306753/211171246-663670e7-e60d-47b6-a3a1-18495d98cfd3.png)

**Desktop (please complete the following information):**
 - OS: windows
 - AST Version: 0.2.4
 - EDMC Version: 5.7.0

**Additional context**
Have verified that finishing a scan, and starting a new one, on another planet, wasn't going to kick-start the process.

**Comment by slippycheeze** [comment]
I can confirm that this change to `load.py` fixes the bug on my side, when manually applied.
Thank you so much for the fast response, and the plugin.

**Comment by Balvald** [comment]
yay c:

Though I thought with me forgetting little things that bug me afterwards.
I think it'll be high time to open another repo to write and store tests so that I don't accidentially make things worse at some point.
