### ISSUE TITLE
[BUG] No longer appearing in EDMC v. 5.9.4

### ISSUE THREAD

**Issue by DigitalJaguar** [Balvald/ArtemisScannerTracker#56]
**Describe the bug**
The current version, 0.2.7, does not appear in EDMC 5.9.4.

**To Reproduce**
Install version 0.2.7 with the most recent version of EDMC. No AST section appears in either the window or the plugin settings.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - AST Version: 0.2.7
 - EDMC Version: 5.9.4

**Additional context**
0.2.6 does appear with the update available notice.

**Comment by Balvald** [comment]
I can't reproduce this. I have it installed on 5.9.4 and it works "fine" (apart from a different bug I'm currently debugging.)

About E:D Market Connector lists the version I currently work on the plugin as: 5.9.4+6e8f881 (after + is the hash of the commit that the release is based on)

If 0.2.6 works have you checked if the folder structure is any different if you have both 0.2.7 and 0.2.6 installed?
(as in where the load.py is located compared to where the plugin folders need to be)

If thats not the case please provide a edmc log from just when you start up the plugin with them correctly installed.

**Comment by Balvald** [comment]
changed title to be in the same format as other bug reports

**Comment by DigitalJaguar** [comment]
Well, this one's a bit of a head scratcher for me. 

In my defense, I had tried reinstalling the plugin to the plugin directory before submitting the bug ticket, with no luck, EDMC still didn't see it.

I downloaded the 0.2.7 zip and put a fresh copy into the directory, so I could compare it to the one I already had and to the old 0.2.6 folder. I didn't notice any differences, so I disabled the old one and relaunched EDMC. Surprise, surprise, it's functional and recognized. So I remove the old one, then on a whim, I restore it and enable it and now it's working fine too!

I can't get it to replicate the problem from before now, so I'm at a loss as to what happened

**Comment by Balvald** [comment]
Weird.

I'll keep this one open and will try the first install experience once on a newly formatted machine once I'm finished with a fix for #48 because its the most pressing problem right now.

Since this one suddenly disappeared again.

Worst case I'm hunting ghosts that don't exist,
Best case I actually find something wrong with it and can fix it later.
